"""Observable cache and resume outcomes for persistent work state."""

import json
import subprocess
from dataclasses import replace
from pathlib import Path

import pytest

import gemini_subs
from tests.support.workdir import FakeMediaTools


def make_config(tmp_path, monkeypatch, **overrides):
    video = tmp_path / "source.mp4"
    video.write_bytes(b"video")
    monkeypatch.setattr(
        gemini_subs,
        "probe_video_format",
        lambda _path: (".mp4", "video/mp4", "h264"),
    )
    monkeypatch.setattr(gemini_subs, "CHUNK_ROOT", str(tmp_path / "work_root"))
    values = {
        "video_path": video,
        "output_path": tmp_path / "output.vtt",
        "model": "model",
        "api_key": "key",
        "chunk_dur": 60,
        "overlap": 0,
        "workers": 7,
        "thinking_level": "high",
    }
    values.update(overrides)
    return gemini_subs.GenerationConfig(**values)


def leave_resumable_failure(config, monkeypatch):
    tools = FakeMediaTools()
    monkeypatch.setattr(gemini_subs.subprocess, "run", tools.run)
    monkeypatch.setattr(gemini_subs, "process_chunk", lambda *_args: False)

    with pytest.raises(RuntimeError, match="Failed to process"):
        gemini_subs.run_generation(config)

    return {path.name for path in (Path(gemini_subs.CHUNK_ROOT)).iterdir()}


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("model", "other-model"),
        ("chunk_dur", 30),
        ("overlap", 1),
        ("thinking_level", "medium"),
    ],
)
def test_chunk_generation_changes_create_separate_resume_state(
    tmp_path, monkeypatch, field, value
):
    config = make_config(tmp_path, monkeypatch)
    first = leave_resumable_failure(config, monkeypatch)

    second = leave_resumable_failure(replace(config, **{field: value}), monkeypatch)

    assert len(first) == 1
    assert len(second) == 2


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("output_path", Path("other.vtt")),
        ("workers", 2),
        ("refine_model", "other-refiner"),
        ("refine_text", False),
        ("api_key", "other-key"),
        ("base_url", "https://proxy.example"),
        ("context_urls", ("https://example.com/notes",)),
    ],
)
def test_non_chunk_options_reuse_existing_resume_state(
    tmp_path, monkeypatch, field, value
):
    config = make_config(tmp_path, monkeypatch)
    first = leave_resumable_failure(config, monkeypatch)
    if field == "output_path":
        value = tmp_path / value

    second = leave_resumable_failure(replace(config, **{field: value}), monkeypatch)

    assert len(first) == 1
    assert second == first


def test_changing_the_source_file_creates_separate_resume_state(tmp_path, monkeypatch):
    config = make_config(tmp_path, monkeypatch)
    first = leave_resumable_failure(config, monkeypatch)
    config.video_path.write_bytes(b"changed content")

    second = leave_resumable_failure(config, monkeypatch)

    assert len(first) == 1
    assert len(second) == 2


def test_split_publishes_manifest_segments_and_completion_marker(tmp_path, monkeypatch):
    tools = FakeMediaTools()
    monkeypatch.setattr(gemini_subs.subprocess, "run", tools.run)
    work = tmp_path / "work"
    work.mkdir()

    gemini_subs.split_video("source.mp4", str(work), 60, {"chunk_ext": ".mp4"})

    assert (work / gemini_subs.MANIFEST_NAME).is_file()
    assert (work / "segments.csv").is_file()
    assert (work / gemini_subs.SPLIT_COMPLETE_MARKER).read_text(
        encoding="utf-8"
    ) == "ok\n"
    assert sorted(path.name for path in work.glob("chunk_*")) == [
        "chunk_000.mp4",
        "chunk_001.mp4",
    ]


def test_completed_split_is_reused_without_regenerating_chunks(tmp_path, monkeypatch):
    tools = FakeMediaTools()
    monkeypatch.setattr(gemini_subs.subprocess, "run", tools.run)
    work = tmp_path / "work"
    work.mkdir()
    manifest = {"chunk_ext": ".mp4"}

    gemini_subs.split_video("source.mp4", str(work), 60, manifest)
    tools.chunk_bytes = b"regenerated bytes"
    gemini_subs.split_video("source.mp4", str(work), 60, manifest)

    assert len(tools.split_calls()) == 1
    assert (work / "chunk_000.mp4").read_bytes() == b"fake chunk"
    assert (work / "chunk_001.mp4").read_bytes() == b"fake chunk"


def test_incomplete_split_is_regenerated_and_marker_restored(tmp_path, monkeypatch):
    tools = FakeMediaTools()
    monkeypatch.setattr(gemini_subs.subprocess, "run", tools.run)
    work = tmp_path / "work"
    work.mkdir()
    Path(work, "segments.csv").write_text(
        "chunk_000.mp4,0,2\nchunk_001.mp4,2,4\n", encoding="utf-8"
    )
    Path(work, "chunk_000.mp4").write_bytes(b"partial")
    marker = Path(work, gemini_subs.SPLIT_COMPLETE_MARKER)
    marker.write_text("ok\n", encoding="utf-8")

    gemini_subs.split_video("source.mp4", str(work), 60, {"chunk_ext": ".mp4"})

    assert marker.read_text(encoding="utf-8") == "ok\n"
    assert (work / "chunk_000.mp4").read_bytes() == b"fake chunk"
    assert (work / "chunk_001.mp4").read_bytes() == b"fake chunk"


def test_failed_split_removes_the_completion_marker(tmp_path, monkeypatch):
    work = tmp_path / "work"
    work.mkdir()
    marker = Path(work, gemini_subs.SPLIT_COMPLETE_MARKER)
    marker.write_text("ok\n", encoding="utf-8")
    Path(work, "segments.csv").write_text("chunk_000.mp4,0,2\n", encoding="utf-8")

    def fail(_command, **_kwargs):
        raise subprocess.CalledProcessError(1, "ffmpeg")

    monkeypatch.setattr(gemini_subs.subprocess, "run", fail)

    with pytest.raises(subprocess.CalledProcessError):
        gemini_subs.split_video("source.mp4", str(work), 60, {"chunk_ext": ".mp4"})

    assert not marker.exists()


def test_valid_overlap_clip_cache_is_reused_without_reencoding(tmp_path, monkeypatch):
    work = tmp_path / "work"
    work.mkdir()
    clip = Path(work, "context_chunk_000.mp4")
    clip.write_bytes(b"cached clip")
    tools = FakeMediaTools(probe_duration="2.5\n", clip_bytes=b"fresh clip")
    monkeypatch.setattr(gemini_subs.subprocess, "run", tools.run)

    result = gemini_subs.create_overlap_clip("source.mp4", str(work), 0, 0, 2.5, ".mp4")

    assert result == "context_chunk_000.mp4"
    assert clip.read_bytes() == b"cached clip"


def test_corrupted_overlap_clip_is_replaced_without_temporary_files(
    tmp_path, monkeypatch
):
    work = tmp_path / "work"
    work.mkdir()
    clip = Path(work, "context_chunk_000.mp4")
    clip.write_bytes(b"corrupt clip")
    Path(work, gemini_subs.MANIFEST_NAME).write_text(
        json.dumps({"video_codec": "h264"}), encoding="utf-8"
    )
    tools = FakeMediaTools(probe_ok=False, clip_bytes=b"fresh clip")
    monkeypatch.setattr(gemini_subs.subprocess, "run", tools.run)

    result = gemini_subs.create_overlap_clip(
        "source.mp4", str(work), 0, 1.25, 4.75, ".mp4"
    )

    assert result == "context_chunk_000.mp4"
    assert clip.read_bytes() == b"fresh clip"
    assert not Path(f"{clip}.tmp").exists()
