"""Split and overlap clip cache reuse outcomes."""

import json
import subprocess
from pathlib import Path

import pytest

from modules import io, media
from tests.support.workdir import FakeMediaTools


def test_split_publishes_manifest_segments_and_completion_marker(tmp_path, monkeypatch):
    tools = FakeMediaTools()
    monkeypatch.setattr(media.subprocess, "run", tools.run)
    work = tmp_path / "work"
    work.mkdir()

    media.split_video("source.mp4", str(work), 60, {"chunk_ext": ".mp4"})

    assert (work / io.MANIFEST_NAME).is_file()
    assert (work / "segments.csv").is_file()
    assert (work / media.SPLIT_COMPLETE_MARKER).read_text(encoding="utf-8") == "ok\n"
    assert sorted(path.name for path in work.glob("chunk_*")) == [
        "chunk_000.mp4",
        "chunk_001.mp4",
    ]


def test_completed_split_is_reused_without_regenerating_chunks(tmp_path, monkeypatch):
    tools = FakeMediaTools()
    monkeypatch.setattr(media.subprocess, "run", tools.run)
    work = tmp_path / "work"
    work.mkdir()
    manifest = {"chunk_ext": ".mp4"}

    media.split_video("source.mp4", str(work), 60, manifest)
    tools.chunk_bytes = b"regenerated bytes"
    media.split_video("source.mp4", str(work), 60, manifest)

    assert len(tools.split_calls()) == 1
    assert (work / "chunk_000.mp4").read_bytes() == b"fake chunk"
    assert (work / "chunk_001.mp4").read_bytes() == b"fake chunk"


def test_incomplete_split_is_regenerated_and_marker_restored(tmp_path, monkeypatch):
    tools = FakeMediaTools()
    monkeypatch.setattr(media.subprocess, "run", tools.run)
    work = tmp_path / "work"
    work.mkdir()
    Path(work, "segments.csv").write_text(
        "chunk_000.mp4,0,2\nchunk_001.mp4,2,4\n", encoding="utf-8"
    )
    Path(work, "chunk_000.mp4").write_bytes(b"partial")
    marker = Path(work, media.SPLIT_COMPLETE_MARKER)
    marker.write_text("ok\n", encoding="utf-8")

    media.split_video("source.mp4", str(work), 60, {"chunk_ext": ".mp4"})

    assert marker.read_text(encoding="utf-8") == "ok\n"
    assert (work / "chunk_000.mp4").read_bytes() == b"fake chunk"
    assert (work / "chunk_001.mp4").read_bytes() == b"fake chunk"


def test_failed_split_removes_the_completion_marker(tmp_path, monkeypatch):
    work = tmp_path / "work"
    work.mkdir()
    marker = Path(work, media.SPLIT_COMPLETE_MARKER)
    marker.write_text("ok\n", encoding="utf-8")
    Path(work, "segments.csv").write_text("chunk_000.mp4,0,2\n", encoding="utf-8")

    def fail(_command, **_kwargs):
        raise subprocess.CalledProcessError(1, "ffmpeg")

    monkeypatch.setattr(media.subprocess, "run", fail)

    with pytest.raises(subprocess.CalledProcessError):
        media.split_video("source.mp4", str(work), 60, {"chunk_ext": ".mp4"})

    assert not marker.exists()


def test_valid_overlap_clip_cache_is_reused_without_reencoding(tmp_path, monkeypatch):
    work = tmp_path / "work"
    work.mkdir()
    clip = Path(work, "context_chunk_000.mp4")
    clip.write_bytes(b"cached clip")
    tools = FakeMediaTools(probe_duration="2.5\n", clip_bytes=b"fresh clip")
    monkeypatch.setattr(media.subprocess, "run", tools.run)

    result = media.create_overlap_clip("source.mp4", str(work), 0, 0, 2.5, ".mp4")

    assert result == "context_chunk_000.mp4"
    assert clip.read_bytes() == b"cached clip"


def test_corrupted_overlap_clip_is_replaced_without_temporary_files(
    tmp_path, monkeypatch
):
    work = tmp_path / "work"
    work.mkdir()
    clip = Path(work, "context_chunk_000.mp4")
    clip.write_bytes(b"corrupt clip")
    Path(work, io.MANIFEST_NAME).write_text(
        json.dumps({"video_codec": "h264"}), encoding="utf-8"
    )
    tools = FakeMediaTools(probe_ok=False, clip_bytes=b"fresh clip")
    monkeypatch.setattr(media.subprocess, "run", tools.run)

    result = media.create_overlap_clip("source.mp4", str(work), 0, 1.25, 4.75, ".mp4")

    assert result == "context_chunk_000.mp4"
    assert clip.read_bytes() == b"fresh clip"
    assert not Path(f"{clip}.tmp").exists()
